Weapons/community-review/readme.md
Weapons/community-review/sanction-list.csv

Community weapons review

---

Weapons/community-review/sanction-list.csv

Assign none to all unassigned MAX weapons

---

Weapons/community-review/sanction-list.csv

Explosives & Grenades to 'none' to match others

---

Weapons/community-review/sanction-list.csv

Harraser new guns to 'gunner'

---

Weapons/community-review/sanction-list.csv

MBT Aphelion, Gatekeeper, Mjolnir to 'gunner'

---

Weapons/community-review/sanction-list.csv

Rocklet, Rocket Launchers to 'none' to match other

---

Weapons/community-review/sanction-list.csv

Update Valkyrie to 'none' to match others

---

Weapons/community-review/sanction-list.csv

Sunderer guns to 'gunner' to match others

---

Weapons/community-review/sanction-list.csv

Thumper 'none' with heavy weaps, archer 'infantry'

---

Weapons/community-review/sanction-list-machine.csv
Weapons/community-review/sanction-list.csv

Lightning weapons to 'armor' to match existing

---

Weapons/community-review/sanction-list.csv

Little Helper to 'none' to match other Barons

---

Weapons/community-review/sanction-list-machine.csv
Weapons/community-review/sanction-list.csv

Infantry Abilities to match existing sanctions

---

Weapons/community-review/sanction-list.csv

Construction stuff to 'none'

---

Weapons/community-review/sanction-list-machine.csv
Weapons/community-review/sanction-list.csv

Hammerhead to 'infantry' with other Archers

---

Weapons/community-review/sanction-list.csv

Name NS-66 Punisher SE

---

Weapons/community-review/sanction-list-machine-with-none.csv
Weapons/community-review/sanction-list.csv

Hardlight Barriers, Snowmen to 'none'

---

Weapons/community-review/sanction-list.csv

Pummeler Rocket Pods to Wasp category

---

Weapons/da-sanction-list.csv

Fix quoting on Butcher

---

Weapons/da-sanction-list.csv

Fix quoting on ravenous/brass/heatwave

---

Weapons/da-sanction-list.csv

Fix brass pilot quoting

---

Weapons/sanction-list.csv

**Still needs to all be classified with proper sanctions**

Add in entries for all _Integration weapons

---

README.md

Add PS2Alert.me service and repository links.

Add PS2Alert.me

---

Weapons/sanction-list.csv

Sanctions: Update weapon names changed in API

---

Weapons/sanction-list.csv

Sanction list: update unknown name format

---

Weapons/sanction-list.csv

Sanction List: Add is_vehicle_weapon & faction_id

---

Weapons/sanction-list.csv

Sanctions: Add definition for Seeker HLX

---

Weapons/sanction-list.csv

Strange placeholder addition, documentation provided by Rhett 
https://discord.com/channels/251073753759481856/451032574538547201/907683876216913961

Add Jack Johnson and Tom O'Leary

---

Weapons/sanction-list.csv

Sanction: Add Deliverer, relabel Dervish weapons

---

Weapons/sanction-list.csv

Sanctions: Omit name/category if unknown

---

Weapons/sanction-list.csv

Sanctions: Add Party Pistol, Crystal Scorpion

---

Weapons/sanction-list.csv

Sanctions: Unclassified entries for Arsenal Update

---

Weapons/sanction-list.csv

Fix vehicle weapon flags on 11-year anniversary weapons

Sanctions: Correct 11-year anniversary v-weapon

---

Weapons/list.js
Weapons/sanction-list.csv

Sort item names first by their base name, then by their quoted name part
Example Before:
```
6013950,SMG,0,"NS-66 ""Alchemist"" Punisher",0,infantry
6015320,SMG,0,"NS-66 ""Cold Fusion"" Punisher",,infantry
6013051,SMG,0,NS-66 Bumblebee,,infantry
6009203,SMG,0,NS-66 Punisher,,infantry
6010117,SMG,0,NS-66 Punisher SE,,infantry
```
Example After:
```
6013051,SMG,0,NS-66 Bumblebee,,infantry
6009203,SMG,0,NS-66 Punisher,,infantry
6013950,SMG,0,"NS-66 ""Alchemist"" Punisher",0,infantry
6015320,SMG,0,"NS-66 ""Cold Fusion"" Punisher",,infantry
6010117,SMG,0,NS-66 Punisher SE,,infantry
```

Sanctions: Update list sorting
